# Generated by Django 3.0.5 on 2021-09-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridgeName', models.CharField(max_length=60)),
                ('bridgeDescription', models.TextField()),
                ('bridgeImg', models.ImageField(upload_to='bridge_img')),
            ],
        ),
    ]
