# Generated by Django 3.2.7 on 2021-09-21 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='limbIndexDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limbDiagnosis', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='limbIndexRutherford',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limbRutherford', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='limbIndexSym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limbSymptoms', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='limbNonSurgicalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonSurgical', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='limbSurgicalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgical', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='vascularBridgeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffName', models.CharField(choices=[('napaporn', 'Napaporn'), ('ratana', 'Ratana')], max_length=100)),
                ('nurseManager', models.CharField(choices=[('napaporn', 'Napaporn'), ('ratana', 'Ratana')], max_length=60)),
                ('healthInsurance', models.CharField(choices=[('1', 'Social Security'), ('2', 'Private')], max_length=30)),
                ('educationLevel', models.CharField(choices=[('1', 'K1-K6'), ('2', 'K6-K12'), ('3', 'AS/AA'), ('4', 'BS')], max_length=20)),
                ('occupation', models.CharField(choices=[('1', 'goverment'), ('2', 'Private'), ('3', 'Self-Employed')], max_length=30)),
                ('living', models.CharField(choices=[], max_length=30)),
                ('baseline', models.CharField(choices=[], max_length=30)),
                ('ql_movement', models.CharField(choices=[], max_length=30)),
                ('ql_selfcare', models.CharField(choices=[], max_length=30)),
                ('ql_activities', models.CharField(choices=[], max_length=30)),
                ('ql_selfcomfortable', models.CharField(choices=[], max_length=30)),
                ('ql_anxiety', models.CharField(choices=[], max_length=30)),
                ('leftLimbIndex', models.CharField(max_length=100)),
                ('leftLimbRutherford', models.CharField(max_length=100)),
                ('rightLimbIndex', models.CharField(max_length=100)),
                ('rightLimbRutherford', models.CharField(max_length=100)),
                ('priorintervention', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('leftLimbDiagnosis', models.CharField(max_length=20)),
                ('rightLimbDiagnosis', models.CharField(max_length=20)),
                ('nonInvasiveTest', models.CharField(choices=[('completed', 'Completed'), ('unknown', 'Unknown')], max_length=10)),
                ('woundScore', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], help_text='[0 - No Ulcer(Ischemic rest pain, no wound)] \n [1 - Small Shallow ulcer on distal leg or foot without gangrenous] \n [2 - Deeper ulcer with exposed bone, joint, or tendon, or gangrenous changes limited to digits] \n [3 - Extensive deep ulcer, full thickness heel ulcer, +- calcaneal involvement +- extensive gangrene]', max_length=5)),
                ('ischaemiaScore', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], max_length=5)),
                ('footinfectionScore', models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], max_length=5)),
                ('planSurgical', models.CharField(max_length=10)),
                ('OrPlanDate', models.DateTimeField(auto_now_add=True)),
                ('patientName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
