# Generated by Django 3.2.7 on 2021-09-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vascularbridge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vascularbridgeregister',
            name='OrPlanDate',
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='planNonSurgical',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
