# Generated by Django 3.0.5 on 2021-09-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vascularbridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='education',
            field=models.CharField(choices=[('1', 'K1-K6'), ('2', 'K6-K12'), ('3', 'AS/AA'), ('4', 'BS')], default='--', max_length=20),
        ),
    ]
