# Generated by Django 3.2.7 on 2021-09-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vascularbridge', '0002_auto_20210921_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='OrPlanDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
