# Generated by Django 3.0.5 on 2021-09-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vascularbridge', '0002_vascularbridgeregister_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vascularbridgeregister',
            name='education',
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='educationLevel',
            field=models.CharField(choices=[('1', 'K1-K6'), ('2', 'K6-K12'), ('3', 'AS/AA'), ('4', 'BS')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
