# Generated by Django 3.2.7 on 2021-09-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vascularbridge', '0003_vascularbridgeregister_orplandate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='preOpAppt',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='preOpApptdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vascularbridgeregister',
            name='OrPlanDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
