# Generated by Django 3.2.7 on 2021-09-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vascularbridge', '0003_auto_20210915_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='limbIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limbSide', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('both', 'Both')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='baseline',
            field=models.CharField(choices=[], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='living',
            field=models.CharField(choices=[], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='occupation',
            field=models.CharField(choices=[('1', 'goverment'), ('2', 'Private'), ('3', 'Self-Employed')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='ql_activities',
            field=models.CharField(choices=[], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='ql_anxiety',
            field=models.CharField(choices=[], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='ql_movement',
            field=models.CharField(choices=[], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='ql_selfcare',
            field=models.CharField(choices=[], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='ql_selfcomfortable',
            field=models.CharField(choices=[], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vascularbridgeregister',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='limbIndexSide',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vascularbridge.limbindex'),
            preserve_default=False,
        ),
    ]
