# Generated by Django 3.2.7 on 2021-12-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vascularbridge', '0004_auto_20210921_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='note',
            field=models.TextField(default='None'),
            preserve_default=False,
        ),
    ]
