# Generated by Django 3.2.7 on 2021-09-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vascularbridge', '0005_auto_20210918_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='limbIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='vascularbridgeregister',
            name='leftLimbIndex',
            field=models.CharField(max_length=30),
        ),
        migrations.RemoveField(
            model_name='vascularbridgeregister',
            name='rightLimbIndex',
        ),
        migrations.DeleteModel(
            name='limbIndexSym',
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='rightLimbIndex',
            field=models.ManyToManyField(to='vascularbridge.limbIndex'),
        ),
    ]
