# Generated by Django 3.2.7 on 2021-09-18 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vascularbridge', '0006_auto_20210918_0730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='limbIndex',
            new_name='limbIndexSym',
        ),
    ]
