# Generated by Django 3.2.7 on 2021-09-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vascularbridge', '0008_auto_20210918_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='limbIndexRutherford',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limbRutherford', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='leftLimbRutherford',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='rightLimbRutherford',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='limbindexsym',
            name='limbSymptoms',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vascularbridgeregister',
            name='leftLimbIndex',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='vascularbridgeregister',
            name='rightLimbIndex',
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='rightLimbIndex',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
