# Generated by Django 3.2.7 on 2021-09-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vascularbridge', '0009_auto_20210918_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='limbIndexDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limbDiagnosis', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='leftLimbDiagnosis',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='priorintervention',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='rightLimbDiagnosis',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
