# Generated by Django 3.2.7 on 2021-09-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vascularbridge', '0010_auto_20210918_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='limbPlansurgical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgical', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='footinfectionScore',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='ischaemiaScore',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='nonInvasiveTest',
            field=models.CharField(choices=[('completed', 'Completed'), ('unknown', 'Unknown')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='planSurgical',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vascularbridgeregister',
            name='woundScore',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3')], default='', help_text='[0 - No Ulcer(Ischemic rest pain, no wound)] \n [1 - Small Shallow ulcer on distal leg or foot without gangrenous] \n [2 - Deeper ulcer with exposed bone, joint, or tendon, or gangrenous changes limited to digits] \n [3 - Extensive deep ulcer, full thickness heel ulcer, +- calcaneal involvement +- extensive gangrene]', max_length=5),
            preserve_default=False,
        ),
    ]
