# Generated by Django 3.2.7 on 2021-12-19 00:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthlit', '0002_alter_program_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subprogramName', models.CharField(max_length=100, verbose_name='Name of the sub-program')),
                ('subprogramDescription', models.TextField(verbose_name='Description of this sub-program')),
                ('datePosted', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='programUrl',
            field=models.CharField(default='vascular', max_length=60, verbose_name='Program name without space'),
            preserve_default=False,
        ),
    ]
