# Generated by Django 3.2.7 on 2021-12-19 02:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthlit', '0003_auto_20211219_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='confirmedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patName', models.CharField(max_length=100, verbose_name='Patient Name')),
                ('datePosted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
