# Generated by Django 3.2.7 on 2021-12-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthlit', '0004_confirmedcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedcase',
            name='patName',
            field=models.CharField(max_length=100, verbose_name='PatientName'),
        ),
    ]
