# Generated by Django 3.2.7 on 2021-12-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthlit', '0005_alter_confirmedcase_patname'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedcase',
            name='patProgram',
            field=models.CharField(default='vascular', max_length=100, verbose_name='Program Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confirmedcase',
            name='patName',
            field=models.CharField(max_length=100, verbose_name='Patient Name'),
        ),
    ]
